// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByQYKBzcIL3sjrEkOLT9wjaOjH_-0VxQs',
    appId: '1:170017535362:web:c4cf2a0b945aa3f9cd4b9b',
    messagingSenderId: '170017535362',
    projectId: 'oracle-asgard',
    authDomain: 'oracle-asgard.firebaseapp.com',
    storageBucket: 'oracle-asgard.firebasestorage.app',
    measurementId: 'G-SV8PHPPMZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw_1d4qjPfssrpT_fgEcleNx1ZIc7wRVg',
    appId: '1:170017535362:android:9cde7182d4fe81c9cd4b9b',
    messagingSenderId: '170017535362',
    projectId: 'oracle-asgard',
    storageBucket: 'oracle-asgard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtbUCdPCLqh1pJU5tOdqltxqrERFh9BTI',
    appId: '1:170017535362:ios:96195e1f83db49a4cd4b9b',
    messagingSenderId: '170017535362',
    projectId: 'oracle-asgard',
    storageBucket: 'oracle-asgard.firebasestorage.app',
    iosBundleId: 'com.example.personalOracle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtbUCdPCLqh1pJU5tOdqltxqrERFh9BTI',
    appId: '1:170017535362:ios:374eb65cef3df81fcd4b9b',
    messagingSenderId: '170017535362',
    projectId: 'oracle-asgard',
    storageBucket: 'oracle-asgard.firebasestorage.app',
    iosBundleId: 'com.example.oracleDAsgard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByQYKBzcIL3sjrEkOLT9wjaOjH_-0VxQs',
    appId: '1:170017535362:web:adea2cdc0f351df7cd4b9b',
    messagingSenderId: '170017535362',
    projectId: 'oracle-asgard',
    authDomain: 'oracle-asgard.firebaseapp.com',
    storageBucket: 'oracle-asgard.firebasestorage.app',
    measurementId: 'G-9HM2W4LDJW',
  );

}