[[command]]
name = "release"
description = "Create and publish a new release."

[[command.step]]
name = "Increment version"
description = "Increment the build number in pubspec.yaml."
run = """
current_version=$(grep 'version: ' pubspec.yaml | awk '{print $2}')
base_version=$(echo $current_version | cut -d'+' -f1)
build_number=$(echo $current_version | cut -d'+' -f2)
new_build_number=$((build_number + 1))
new_version="${base_version}+${new_build_number}"
sed -i '' "s/version: ${current_version}/version: ${new_version}/" pubspec.yaml
echo "Version bumped to ${new_version}"
"""

[[command.step]]
name = "Commit changes"
description = "Commit the version bump."
run = """
new_version=$(grep 'version: ' pubspec.yaml | awk '{print $2}')
git add pubspec.yaml
git commit -F <(echo "chore(release): bump version to ${new_version}" | base64 --decode)
"""

[[command.step]]
name = "Create tag"
description = "Create a git tag for the new version."
run = """
new_version=$(grep 'version: ' pubspec.yaml | awk '{print $2}')
git tag "v${new_version}"
"""

[[command.step]]
name = "Push to origin"
description = "Push commits and tags to the origin remote."
run = "git push origin && git push origin --tags"

[[command.step]]
name = "Open Google Play Console"
description = "Open the internal testing track in Google Play Console."
run = "open -a 'Google Chrome' 'https://play.google.com/console/u/0/developers/7678706771924505759/app/4972955630697428940/tracks/internal-testing'"